[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pk-core"
authors = [
  { name="Tulare Regnus", email="tulare.paxgalactica@gmail.com" },
]
description = "Core utils for python projects"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["python","utilities","core"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/tulare/pk-core"

[tool.setuptools.dynamic]
version = {attr = "pk_core.__version__"}
